### ISSUE TITLE
Images still aren't copied to the dist folder

### ISSUE THREAD

**Issue by stefanedberg** [osynligab/web-starterpack#1]
http://stefan.dev.osynlig.se/dist/

1. git clone
2. npm i
3. gulp
4. Made sure style and js was compiled
5. gulp release

Fix this, test the old browser message (in IE7/8/9) and apply this on all our active projects.

@iamjonas @osynligsebastian

**Comment by iamjonas** [comment]
``!${PATHS.src}/images/icons*.svg``

ignoring .svg files within image task
